# Generated by Django 2.0 on 2018-12-05 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=10, verbose_name='商品编码')),
                ('user_id', models.CharField(max_length=10, verbose_name='设计师')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('image', models.ImageField(upload_to='media/image/%Y/%m')),
            ],
            options={
                'verbose_name': '商品编码',
                'verbose_name_plural': '商品编码',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muchs', models.IntegerField(default=0, verbose_name='数量')),
                ('pici', models.IntegerField(default=0, verbose_name='批次')),
            ],
            options={
                'verbose_name': '下单',
                'verbose_name_plural': '下单',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('hs', '红色'), ('ls', '蓝色')], max_length=30, verbose_name='颜色')),
                ('size', models.CharField(choices=[('1', '长款'), ('0', '短款')], max_length=30, verbose_name='袖长')),
                ('shangjia_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='记录时间')),
                ('image', models.ImageField(upload_to='media/image/%Y/%m')),
                ('bianma', models.CharField(blank=True, max_length=20, null=True)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='编码')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bianma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Shop', verbose_name='下单编码'),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('good_id', 'color', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('bianma', 'pici'), ('pici', 'bianma')},
        ),
    ]
