# Generated by Django 2.0 on 2018-12-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pici',
            field=models.IntegerField(blank=True, verbose_name='批次'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
